### ISSUE TITLE
Incorrect set value into array typed attribute

### ISSUE THREAD

**Issue by GruFFix** [wearevolt/mobx-model-json-api#1]
After creating a Model overwritten a simple array to an array of objects, this is answer from the server :
![1](https://cloud.githubusercontent.com/assets/16576776/21377948/391c5e10-c764-11e6-894c-793afba1b5ae.jpg)
and what we have after in Model :
![2](https://cloud.githubusercontent.com/assets/16576776/21377959/4a2a3c2c-c764-11e6-8655-b2af1f99cdac.jpg)
How can I get a simple array in the Model?

**Comment by Staltec** [comment]
Fixed
